loss:
  _target_: silk.losses.info_nce.Loss
  block_size: 5400
  device: "cuda:0"
  temperature: 0.1

contextualizer: null
ghost_similarity: null
learn_ghost_similarity: false
feature_downsampling_mode: "padding"
greyscale_input: True
optimizer_spec:
  _target_: silk.config.optimizer.Spec
  optimizer_class: torch.optim.Adam
  # lr: 0.00002
  lr: 0.0001
  # lr: 0.00005
  betas:
    - 0.9
    - 0.999
image_aug_transform:
  # augmentation used for IMC (4.3) and ScanNet (4.4.1)
  _target_: silk.transforms.cv.image.Albu
  _args_:
    - _target_: albumentations.Compose
      p: 0.95
      transforms:
        - _target_: albumentations.RandomGamma
          p: 0.1
          gamma_limit: [15, 65]
        - _target_: albumentations.HueSaturationValue
          p: 0.1
          val_shift_limit: [-100, -40]
        - _target_: albumentations.Blur
          p: 0.1
          blur_limit: [3, 9]
        - _target_: albumentations.MotionBlur
          p: 0.2
          blur_limit: [3, 25]
        - _target_: albumentations.RandomBrightnessContrast
          p: 0.5
          brightness_limit: [-0.3, 0.0]
          contrast_limit: [-0.5, 0.3]
        - _target_: albumentations.GaussNoise
          p: 0.5

