defaults:
  - benchmark-defaults
  - /models@model: magicpoint-frozen-best
  - /datasets/synthetic-shapes@loader.dataset: test
  - _self_

benchmarker:
  gpus: 1
  limit_test_batches: 5
  metric_updates:
    mAP[class]:
      _target_: silk.transforms.metric.MetricUpdate
      name: null
      metric:
        _target_: torchmetrics.AveragePrecision
        compute_on_step: false
        average: "weighted"
        num_classes: 65
      preds: "@class_probs"
      target: "@class_label"

    AP[binary,dense]:
      _target_: silk.transforms.metric.MetricUpdate
      name: null
      metric:
        _target_: torchmetrics.AveragePrecision
        compute_on_step: false
      preds: "@probs_map"
      target: "@label_map"

    kAP[pre-nms,multimatching]:
      _target_: silk.transforms.metric.MetricUpdate
      name: null
      metric:
        _target_: silk.metrics.keypoint.KeypointDetectionAveragePrecision
        compute_on_step: false
        distance_threshold: 2.0
        allow_multimatching: true
      preds: "@pred_positions_with_prob"
      target: "@positions"

    kAP[pre-nms,no multimatching]:
      _target_: silk.transforms.metric.MetricUpdate
      name: null
      metric:
        _target_: silk.metrics.keypoint.KeypointDetectionAveragePrecision
        compute_on_step: false
        distance_threshold: 2.0
        allow_multimatching: false
      preds: "@pred_positions_with_prob"
      target: "@positions"

    kAP[post-nms,multimatching]:
      _target_: silk.transforms.metric.MetricUpdate
      name: null
      metric:
        _target_: silk.metrics.keypoint.KeypointDetectionAveragePrecision
        compute_on_step: false
        distance_threshold: 2.0
        allow_multimatching: true
      preds: "@nms_pred_positions_with_prob"
      target: "@positions"

    kAP[post-nms,no multimatching]:
      _target_: silk.transforms.metric.MetricUpdate
      name: null
      metric:
        _target_: silk.metrics.keypoint.KeypointDetectionAveragePrecision
        compute_on_step: false
        distance_threshold: 2.0
        allow_multimatching: false
      preds: "@nms_pred_positions_with_prob"
      target: "@positions"

loader:
  batch_size: 20
  num_workers: 12
  collate_fn: ${mode.collate_fn}
  worker_init_fn: ${mode.worker_init_fn}

worker_init_fn:
  _target_: silk.config.core.find_class_or_callable_from_target
  target: silk.datasets.abstract.RandomizedIterable.worker_init_fn

collate_fn:
  _target_: silk.transforms.tensor.AutoBatch
  transform:
    _target_: silk.transforms.abstract.Compose
    _args_:
      # convert tuples to named context
      - _target_: silk.transforms.abstract.Name
        _args_:
          - "image"
          - "positions"
      # convert numpy arrays to tensors
      - _target_: silk.transforms.abstract.Map
        function:
          _target_: silk.transforms.tensor.ToTensor
      # convert positions to label map
      - _target_: silk.transforms.abstract.Lambda
        name: "label_map"
        function:
            _target_: silk.config.core.find_class_or_callable_from_target
            target: silk.backbones.superpoint.utils.positions_to_label_map
        positions: "@positions"
        image_or_shape: "@image"
      # convert image from HWC to CHW format
      - _target_: silk.transforms.abstract.MapOnly
        names:
          - "label_map"
          - "image"
        function:
          _target_: silk.transforms.cv.image.HWCToCHW
      # normalize image values
      - _target_: silk.transforms.abstract.MapOnly
        names:
          - "image"
        function:
          _target_: silk.transforms.tensor.NormalizeRange
          ilow: 0.
          ihigh: 255.
          olow: 0.
          ohigh: 1.
