defaults:
  - defaults

optimizer_class: torch.optim.Adam


# quicktest
# lr: 0.1
# betas:
#   - 0.9
#   - 0.999



# silk
# lr: 0.001
# betas:
#   - 0.9
#   - 0.999

# # sfmlearner 2e-4
lr: 0.0002
betas:
  - 0.9
  - 0.999
