_target_: silk.datasets.cached.CachedDataset

filepath:
  _target_: silk.config.paths.join
  # _args_: [ASSETS, "results", "hpatches", "cached-results", "disk_all_points_240.h5"]
  # _args_: [ASSETS, "results", "hpatches", "cached-results", "disk_all_points_360.h5"]
  _args_: [ASSETS, "results", "hpatches", "cached-results", "disk_all_points_480.h5"]
  # _args_: [ASSETS, "results", "hpatches", "cached-results", "disk_all_points_600.h5"]
  # _args_: [ASSETS, "results", "hpatches", "cached-results", "disk_all_points_720.h5"]
